name: notnotes
description: "Not a Simple Notes."
publish_to: 'none'
version: 0.2.5

environment:
  sdk: ^3.6.2

dependencies:
  build_runner: ^2.4.15
  flex_color_scheme: ^8.1.1
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.12
  font_awesome_flutter: ^10.8.0
  gap: ^3.0.1
  get_it: ^8.0.3
  go_router: ^14.8.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  json_serializable: ^6.9.4
  provider: ^6.1.2
  shared_preferences: ^2.5.2
  toastification: ^3.0.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/notes.json
    - assets/unluck.png
